import { StyleSheet } from 'react-native';
import { tokens, MD3Shapes } from '../theme/tokens';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: tokens.colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
    padding: tokens.spacing.lg,
  },
  // Card M3 Filled/Elevated (Surface Container High, 28dp radius)
  card: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: tokens.colors.surfaceContainerHigh,
    borderWidth: 1,
    borderColor: tokens.colors.outlineVariant,
    borderRadius: MD3Shapes.extraLarge,
    padding: tokens.spacing.xl,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 14,
    elevation: 8,
  },
  topHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: tokens.spacing.sm,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  title: {
    fontSize: tokens.typography.size.headlineMedium,
    fontWeight: tokens.typography.weight.bold,
    color: tokens.colors.onSurface,
    letterSpacing: -0.5,
  },
  brandDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: tokens.colors.primary,
  },
  serverPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: tokens.colors.secondaryContainer,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: MD3Shapes.full,
    borderWidth: 1,
    borderColor: tokens.colors.outlineVariant,
  },
  serverPillText: {
    color: tokens.colors.onSecondaryContainer,
    fontSize: 11,
    fontWeight: tokens.typography.weight.bold,
  },
  subtitle: {
    fontSize: tokens.typography.size.bodyMedium,
    color: tokens.colors.onSurfaceVariant,
    marginBottom: 4,
  },
  serverHostIndicator: {
    fontSize: tokens.typography.size.labelSmall,
    color: tokens.colors.outline,
    marginBottom: tokens.spacing.md,
  },
  errorBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: tokens.colors.errorContainer,
    borderRadius: MD3Shapes.small,
    padding: tokens.spacing.sm + 2,
    marginBottom: tokens.spacing.md,
  },
  errorText: {
    color: tokens.colors.onErrorContainer,
    fontSize: tokens.typography.size.labelMedium,
    fontWeight: tokens.typography.weight.medium,
    flex: 1,
  },
  inputGroup: {
    marginBottom: tokens.spacing.md,
  },
  label: {
    fontSize: tokens.typography.size.labelMedium,
    fontWeight: tokens.typography.weight.medium,
    color: tokens.colors.onSurfaceVariant,
    marginBottom: 6,
  },
  // Outlined Text Field M3
  input: {
    height: 48,
    backgroundColor: tokens.colors.surfaceContainerLow,
    borderWidth: 1,
    borderColor: tokens.colors.outlineVariant,
    borderRadius: MD3Shapes.small,
    paddingHorizontal: tokens.spacing.md,
    color: tokens.colors.onSurface,
    fontSize: tokens.typography.size.bodyLarge,
  },
  passwordInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 48,
    backgroundColor: tokens.colors.surfaceContainerLow,
    borderWidth: 1,
    borderColor: tokens.colors.outlineVariant,
    borderRadius: MD3Shapes.small,
    paddingRight: 6,
  },
  passwordInput: {
    flex: 1,
    height: '100%',
    paddingHorizontal: tokens.spacing.md,
    color: tokens.colors.onSurface,
    fontSize: tokens.typography.size.bodyLarge,
  },
  passwordEyeButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // M3 Filled Primary Button
  primaryButton: {
    backgroundColor: tokens.colors.primary,
    height: 48,
    borderRadius: MD3Shapes.full,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: tokens.spacing.sm,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  primaryButtonText: {
    color: tokens.colors.onPrimary,
    fontSize: tokens.typography.size.labelLarge,
    fontWeight: tokens.typography.weight.bold,
    letterSpacing: 0.2,
  },
  switchButton: {
    marginTop: tokens.spacing.lg,
    alignItems: 'center',
    paddingVertical: 6,
  },
  switchText: {
    color: tokens.colors.primary,
    fontSize: tokens.typography.size.bodySmall,
    fontWeight: tokens.typography.weight.semibold,
  },
  otaFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: tokens.spacing.xl,
    paddingTop: tokens.spacing.md,
    borderTopWidth: 1,
    borderTopColor: tokens.colors.outlineVariant,
  },
  otaText: {
    color: tokens.colors.onSurfaceVariant,
    fontSize: 11,
  },
  checkUpdatesBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: tokens.colors.surfaceContainerHighest,
    borderRadius: MD3Shapes.small,
  },
  checkUpdatesText: {
    color: tokens.colors.onSurface,
    fontSize: 11,
    fontWeight: tokens.typography.weight.semibold,
  },
});
