import { StyleSheet } from 'react-native';
import { tokens, MD3Shapes, ThemeColors } from '../theme/tokens';

export const createAuthStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.surface,
      justifyContent: 'center',
      alignItems: 'center',
      padding: tokens.spacing.lg,
    },
    // Card M3 Filled/Elevated (Surface Container High, 28dp radius)
    card: {
      width: '100%',
      maxWidth: 400,
      backgroundColor: colors.surfaceContainer,
      borderWidth: 1,
      borderColor: colors.outlineVariant,
      borderRadius: MD3Shapes.extraLarge,
      padding: tokens.spacing.xl,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.3,
      shadowRadius: 14,
      elevation: 8,
    },
  topHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: tokens.spacing.sm,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  title: {
    fontSize: tokens.typography.size.headlineMedium,
    fontWeight: tokens.typography.weight.bold,
    color: colors.onSurface,
    letterSpacing: -0.5,
  },
  brandDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.primary,
  },
  themePill: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 32,
    height: 32,
    backgroundColor: colors.surfaceContainerHighest,
    borderRadius: MD3Shapes.full,
    borderWidth: 1,
    borderColor: colors.outlineVariant,
  },
  subtitle: {
    fontSize: tokens.typography.size.bodyMedium,
    color: colors.onSurfaceVariant,
    marginBottom: tokens.spacing.lg,
  },
  errorBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.errorContainer,
    borderRadius: MD3Shapes.small,
    padding: tokens.spacing.sm + 2,
    marginBottom: tokens.spacing.md,
  },
  errorText: {
    color: colors.onErrorContainer,
    fontSize: tokens.typography.size.labelMedium,
    fontWeight: tokens.typography.weight.medium,
    flex: 1,
  },
  inputGroup: {
    marginBottom: tokens.spacing.md,
  },
  label: {
    fontSize: tokens.typography.size.labelMedium,
    fontWeight: tokens.typography.weight.medium,
    color: colors.onSurfaceVariant,
    marginBottom: 6,
  },
  // Outlined Text Field M3
  input: {
    height: 48,
    backgroundColor: colors.surfaceContainerLow,
    borderWidth: 1,
    borderColor: colors.outlineVariant,
    borderRadius: MD3Shapes.small,
    paddingHorizontal: tokens.spacing.md,
    color: colors.onSurface,
    fontSize: tokens.typography.size.bodyLarge,
  },
  passwordInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 48,
    backgroundColor: colors.surfaceContainerLow,
    borderWidth: 1,
    borderColor: colors.outlineVariant,
    borderRadius: MD3Shapes.small,
    paddingRight: 6,
  },
  passwordInput: {
    flex: 1,
    height: '100%',
    paddingHorizontal: tokens.spacing.md,
    color: colors.onSurface,
    fontSize: tokens.typography.size.bodyLarge,
  },
  passwordEyeButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // M3 Filled Primary Button
  primaryButton: {
    backgroundColor: colors.primary,
    height: 48,
    borderRadius: MD3Shapes.full,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: tokens.spacing.sm,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  primaryButtonText: {
    color: colors.onPrimary,
    fontSize: tokens.typography.size.labelLarge,
    fontWeight: tokens.typography.weight.bold,
    letterSpacing: 0.2,
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: tokens.spacing.md,
    gap: tokens.spacing.sm,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.outlineVariant,
  },
  dividerText: {
    fontSize: tokens.typography.size.labelSmall,
    color: colors.onSurfaceVariant,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  googleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 48,
    borderRadius: MD3Shapes.full,
    borderWidth: 1,
    borderColor: colors.outlineVariant,
    backgroundColor: colors.surfaceContainerHigh,
    gap: tokens.spacing.sm,
  },
  googleButtonText: {
    fontSize: tokens.typography.size.labelLarge,
    fontWeight: tokens.typography.weight.bold,
    color: colors.onSurface,
  },
  switchButton: {
    marginTop: tokens.spacing.lg,
    alignItems: 'center',
    paddingVertical: 6,
  },
  switchText: {
    color: colors.primary,
    fontSize: tokens.typography.size.bodySmall,
    fontWeight: tokens.typography.weight.semibold,
  },
  otaFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: tokens.spacing.xl,
    paddingTop: tokens.spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.outlineVariant,
  },
  otaText: {
    color: colors.onSurfaceVariant,
    fontSize: 11,
  },
  checkUpdatesBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: colors.surfaceContainerHighest,
    borderRadius: MD3Shapes.small,
  },
  checkUpdatesText: {
    color: colors.onSurface,
    fontSize: 11,
    fontWeight: tokens.typography.weight.semibold,
  },
});

export const styles = createAuthStyles(tokens.colors);
